name: Build Tampermonkey Scripts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Terser
      run: npm install terser -g

    - name: Build
      run: |
        for file in "quizSleuth" "imSecureEnough"; do
          cat "${file}.meta.js" "${file}.js" > "${file}.user.js"
          terser "${file}.js" --compress 'passes=3,pure_getters,drop_console' --mangle -o "${file}.min.js"
          cat "${file}.meta.js" "${file}.min.js" > "${file}.min.user.js"
          rm -rf "${file}.min.js"
        done

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Built Scripts"
        git push
